[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "msk_modelling_python"
version = "0.2.0"
authors = [
  { name="Your Name", email="basilio_goncalves7@gmail.com" },
]
description = "A Python package for musculoskeletal modelling (initial)"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "numpy-stl",
    # Add other dependencies here
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {file = "setup.py", attr = "__version__"}