[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "msk_modelling_python"
version = "0.2.0"
authors = [
  { name="Bas", email="basilio_goncalves7@gmail.com" },
]
description = "A Python package for musculoskeletal modelling (Beta)"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "numpy-stl",
    # Add other dependencies here
]
dynamic = ["version"]


[tool.setuptools.dynamic]
version = {file = "setup.py", attr = "__version__"}

[distutils]
  index-servers =
    pypi
    PROJECT_NAME

[pypi]
  username = __token__
  password = pypi-AgEIcHlwaS5vcmcCJDIzYjI4Nzc0LTY3NTEtNGIxYy04ZTg0LTMzNGExMTFhMzNlMwACHFsxLFsibXNrLW1vZGVsbGluZy1weXRob24iXV0AAixbMixbIjNiMDMzMDI2LWJkYTUtNDAxZC05ZjQxLTBlMWUwZDQ1MTE2MyJdXQAABiCW4mB2NItosNh3zdCf3WPu4qeMSL_TdBD0AfTbprycxQ
[PROJECT_NAME]
  repository = https://upload.pypi.org/legacy/
  username = __token__
  password = pypi-AgEIcHlwaS5vcmcCJDIzYjI4Nzc0LTY3NTEtNGIxYy04ZTg0LTMzNGExMTFhMzNlMwACHFsxLFsibXNrLW1vZGVsbGluZy1weXRob24iXV0AAixbMixbIjNiMDMzMDI2LWJkYTUtNDAxZC05ZjQxLTBlMWUwZDQ1MTE2MyJdXQAABiCW4mB2NItosNh3zdCf3WPu4qeMSL_TdBD0AfTbprycxQ